<a href="https://colab.research.google.com/github/kwjdals/2020-C-Code/blob/master/01_tf_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
try:
  %tensorflow_version 1.x
except Exception:
  pass

import tensorflow as tf
tf.__version__

'1.15.2'

In [ ]:
import tensorflow as tf

hello = tf.constant("Hellow World!")

sess = tf.Session()
print(sess.run(hello))
sess.close()

b'Hellow World!'


In [ ]:
a = 10
b = 10
print(tf.add(a,b))

sess = tf.Session()
print(sess.run(tf.add(a,b)))
sess.close()

Tensor("Add:0", shape=(), dtype=int32)
20


In [ ]:
%tensorflow_version 2.x

TensorFlow is already loaded. Please restart the runtime to change versions.


In [ ]:
import tensorflow as tf
tf.__version__

'1.15.2'

In [ ]:
a= tf.constant(3)
a

<tf.Tensor 'Const_5:0' shape=() dtype=int32>

In [ ]:
a.shape

TensorShape([])

In [ ]:
a.dtype

tf.int32

In [ ]:
a.numpy()

AttributeError: ignored

In [ ]:
b = tf.constant(3.)
b

<tf.Tensor 'Const_6:0' shape=() dtype=float32>

In [ ]:
b.shape

TensorShape([])

In [ ]:
b.dtype

tf.float32

In [ ]:
b.numpy()

AttributeError: ignored

In [ ]:
a = tf.constant(5)
b = tf.constant(3)
print(a+b)

Tensor("add_3:0", shape=(), dtype=int32)


In [ ]:
c=tf.constant('Hello, World!')
print(c)
print(c.numpy())

Tensor("Const_9:0", shape=(), dtype=string)


AttributeError: ignored

In [ ]:
a= tf.constant([1,2,3])
a.shape

TensorShape([Dimension(3)])

In [ ]:
a = tf.constant([[1,2,3],[4,5,6]])
a.shape

TensorShape([Dimension(2), Dimension(3)])

In [ ]:
a = tf.constant([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a.shape

TensorShape([Dimension(2), Dimension(2), Dimension(3)])

In [ ]:
a

<tf.Tensor 'Const_12:0' shape=(2, 2, 3) dtype=int32>

In [ ]:
x = tf.constant(1.)
bool = tf.constant(True)
res = tf.cond(bool, lambda : tf.add(x,1.), lambda : tf.add(x, 10.))

print(res)
print(res.numpy())

Tensor("cond/Merge:0", shape=(), dtype=float32)


AttributeError: ignored

In [ ]:
tf.Tensor(2.0, shape=(), dtype=float32)
2.0

NameError: ignored

In [ ]:
x = tf.constant(2)
y = tf.constant(5)
def f1():
  return tf.multiply(x, 17)
def f2():
  return tf.add(y, 23)
r = tf.cond(tf.less(x,y),f1,f2)
r.numpy()

AttributeError: ignored

In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([5,6,7])

print((x+y).numpy())

AttributeError: ignored

In [ ]:
a = tf.constant([5],dtype=tf.float32)
b = tf.constant([10],dtype=tf.float32)
c = tf.constant([2],dtype=tf.float32)
print(a.numpy())

d = a*b+c

print(d)
print(d.numpy())

AttributeError: ignored

In [ ]:
x=tf.constant([[0],[10],[20],[30]])
y = tf.constant([0,1,2])

print((x+y).numpy())

AttributeError: ignored

In [ ]:
import numpy as np

print(np.arange(3))
print(np.ones((3,3)))
print()

x = tf.constant(((np.arange(3))))
y = tf.constant([5],dtype=tf.int64)
print(x)
print(y)
print(x+y)

[0 1 2]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Tensor("Const_24:0", shape=(3,), dtype=int64)
Tensor("Const_25:0", shape=(1,), dtype=int64)
Tensor("add_6:0", shape=(3,), dtype=int64)


In [ ]:
x = tf.constant(np.arange(3))
y = tf.constant([5],dtype=tf.int64)
print((x+y).numpy())

x = tf.constant(np.ones((3,3)))
y = tf.constant([5],dtype=tf.double)
print((x+y).numpy())

x = tf.constant(np.arange(3).reshape(3,1))
y = tf.constant(np.arange(3))
print((x+y).numpy())

AttributeError: ignored